name: Build Remnawave Subscription Page (reusable)

on:
  workflow_call:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
        with:
          repository: amster2k2x/remnawave-subscription-page
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run start:build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v7
        with:
          name: frontend-dist
          path: frontend/dist
          if-no-files-found: error
          retention-days: 1

  build:
    needs: build-frontend
    uses: ./.github/workflows/build-and-push-template.yml
    with:
      repo: amster2k2x/remnawave-subscription-page
      display_name: subscription page
      image: ghcr.io/amster2k2x/remnawave-subscription-page
      dockerhub_image: sammosdev/remnawave-subscription-page
      version_file: backend/package.json
      needs_frontend_artifact: true
    secrets: inherit