name: Build Remnawave Frontend (reusable)

on:
  workflow_call:

env:
  IMAGE: ghcr.io/amster2k2x/remnawave-frontend
  DOCKERHUB_IMAGE: sammosdev/remnawave-frontend

jobs:
  notify-tg-start:
    name: Notify Telegram about build start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: amster2k2x/remnawave-frontend
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          fetch-depth: 0
          persist-credentials: false
      
      - name: Send Telegram message with info status
        uses: appleboy/telegram-action@214f06cfa3d3a588c1472116889437e7c6fd29b1 # v1.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }} # Supports forum topics natively!
          format: html
          message: |
            🚀 <b>Build Started</b> 🚀

            <b>Service:</b> Remnawave Frontend
            <b>Trigger:</b> ${{ github.event_name }} by ${{ github.actor }}
            <b>Repository:</b> ${{ github.repository }}

  secret-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: amster2k2x/remnawave-frontend
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0          # Gitleaks needs full history
          persist-credentials: false

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: amster2k2x/remnawave-frontend
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Extract package version
        id: get-version
        run: |
          VERSION=$(jq -r '.version' ./package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.x'
          cache: npm
          cache-dependency-path: ./package-lock.json

      - name: Build frontend
        run: |
          npm ci
          npm run start:build

      - name: Create ZIP archive of /dist
        run: |
          zip -r remnawave-frontend.zip ./dist

      - name: Upload Release Asset
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          files: remnawave-frontend.zip
          tag_name: ${{ steps.get-version.outputs.version }}
          repository: amster2k2x/remnawave-frontend
          token: ${{ secrets.PAT_TOKEN }}
          generate_release_notes: true
          append_body: true
          make_latest: true
          draft: false
          prerelease: false
          name: ${{ steps.get-version.outputs.version }}
          body: |
            # 🌊 Remnawave Frontend v${{ steps.get-version.outputs.version }}

  notify-tg-result:
    name: Notify Telegram about build result
    runs-on: ubuntu-latest
    needs: [build-frontend, secret-scan]
    if: always()
    steps:
      - name: Checkout source code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: amster2k2x/remnawave-frontend
          token: ${{ secrets.PAT_TOKEN }}
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Send Telegram message
        uses: appleboy/telegram-action@214f06cfa3d3a588c1472116889437e7c6fd29b1 # v1.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message_thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
          format: html
          message: |
            ${{ (needs.build-frontend.result == 'success') && '✅ <b>Build Finished Successfully</b>' || '❌ <b>Build Failed</b>' }}

            <b>Service:</b> Remnawave Frontend
            <b>Trigger:</b> ${{ github.event_name }}
            <b>Repository:</b> ${{ github.repository }}

            <b>Pipeline Details:</b>
            • Security Scan: ${{ needs.secret-scan.result }}

            🔗 <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a>
