name: Build Remnawave Backend (reusable)

on:
  workflow_call:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  build:
    uses: ./.github/workflows/build-and-push-template.yml
    with:
      repo: amster2k2x/remnawave-backend
      display_name: Remnawave Backend
      image: ghcr.io/amster2k2x/remnawave-backend
      dockerhub_image: sammosdev/remnawave-backend
      gitleaks_allowlist: |
        paths = [
          '''^configs/xray/''',
          '''^\.env\.sample$'''
        ]
    secrets: inherit
